export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENT = 'SET_INGREDIENT'
export const FAILED_INGREDIENT = 'FAILED_INGREDIENT'

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS'
export const PURCHASE_FAIL = 'PURCHASE_FAIL'
export const PURCHASE_LOADING = 'PURCHASE_LOADING'
export const PURCSHASED_REDIRECT = 'PURCSHASED_REDIRECT'

export const ORDER_FETCH = 'ORDER_FETCH'
export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS'
export const ORDER_FETCH_FAIL = 'ORDER_FETCH_FAIL'
export const ORDER_FETCH_LOADING = 'ORDER_FETCH_LOADING'

export const AUTH_LOAD = 'AUTH_LOAD'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'